# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: java

env:
    - USER_LANGUAGE=en USER_REGION=US VERSION="0.3.${TRAVIS_BUILD_NUMBER}"

os: linux

jdk:
    - oraclejdk8

# Caches mvn repository in order to speed up builds
cache:
    directories:
        - $HOME/.m2
        - $HOME/.npm

before_cache:
    # Remove nifi repo again to save travis from caching it
    - rm -rf $HOME/.m2/repository/org/apache/nifi-registry/

addons:
  chrome: stable

# before_install aids in setting up the Travis-CI environment
#   1. Configures pre-installed Chrome on Travis CI to be used in “headless” mode
before_install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

# before_script aids in setting up the Travis-CI environment
#   1. simulate an `X` server on Travis CI for karma tests that require a GUI
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start

# skip the installation step entirely
install: true

#build commands
script:
    - mvn -T 2C clean install -DskipTests -Dmaven.test.skip=true -Pintegration-tests,contrib-check,jsUnitTests

before_deploy:
    - git config --local user.name "Ruslan Khozinov"
    - git config --local user.email "ruslan.khozinov@gmail.com"
    - git tag ${VERSION}

deploy:
    provider: releases
    api_key:
      secure: "C0fx0hiin8+Hx8H8uX7kIut/ljsH5hrUjzUFpmZhX7AFYHyV5Ds0UoQJmJ/2/nQUoj9zkVRcbTmjG5OtXCtPEHuQ/+KBKnDGIIcDxs8yX1kzEnNcA99v3ZfGjXykpRYP94cPl7nzFUc/ey2tHBXTd64E8Pp38w2GdIbper8XgIL/oji6nBJCOwjmun2KIshseP2IroCXDKM2RcaxrCld3u1WEabyD8HmOPf+9zD/VFOOhhRNlOlP0ubFgvhqCqs/A6qkoCp9FMXF5KkUW+Rao5SoKt4Ybw4YvtzC1U5CvLRtgQ+yPAmYlCL+9PmhvxLcaLLf32uSmPgxGBT0iZobuyJe+oE47F92AxFi00KLKt1tJlyAGRNy2JeuShMjslwW6ae8HLWLgtQwP8gwZElcrliZzzYmdFUFCTZgb8Qjwvnp76yJxesX9VufEzhgyBJ16srXA0bMbXOAZbbMc2INAo+Mch+q6Qk90Ft6qHbcpzg0SYV4P5eABZYNPkeuGB9MqV0JDBrJxgqs+BxPb0jyad8dYmOqFu5AEE1Bo6JezYFHzwT8wIp75acR3YqGpFHPKYgOC5iSPVqkoLhhTpbR1mc9u3chnfw5IpNGJ+A7kcmFWazLX3aEvJFfltHcA3rTHyZ4bZFybuNJdoG3JWvgkjmPrsSA0t9Ppfp3dCS2Hd8="
    skip_cleanup: true
    file: 
        - "./nifi-registry-assembly/target/nifi-registry-${VERSION}-bin.*"
    on:
        repo: ${TRAVIS_REPO_SLUG}
        branch: "*"
        tags: false
